on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: azureakscontainer.azurecr.io
        username: ${{ secrets.acr_azureakscontainer_username }}
        password: ${{ secrets.acr_azureakscontainer_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/StudentAdmissionService" -f  "StudentAdmissionService/Dockerfile" -t azureakscontainer.azurecr.io/myakscluster:${{ github.sha }} --label dockerfile-path=StudentAdmissionService/Dockerfile
        docker push azureakscontainer.azurecr.io/myakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myakscluster94bf | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myakscluster94bf`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myakscluster94bf
        container-registry-url: azureakscontainer.azurecr.io
        container-registry-username: ${{ secrets.acr_azureakscontainer_username }}
        container-registry-password: ${{ secrets.acr_azureakscontainer_password }}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myakscluster94bf
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          azureakscontainer.azurecr.io/myakscluster:${{ github.sha }}
        imagepullsecrets: |
          myaksclusterdockerauth
