on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: azuredemocontainer.azurecr.io
        username: ${{ secrets.acr_azuredemocontainer_username }}
        password: ${{ secrets.acr_azuredemocontainer_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/StudentAdmissionService" -f  "StudentAdmissionService/Dockerfile" -t azuredemocontainer.azurecr.io/azureaks:${{ github.sha }} --label dockerfile-path=StudentAdmissionService/Dockerfile
        docker push azuredemocontainer.azurecr.io/azureaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_azureaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep azureaks90f9 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace azureaks90f9`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: azureaks90f9
        container-registry-url: azuredemocontainer.azurecr.io
        container-registry-username: ${{ secrets.acr_azuredemocontainer_username }}
        container-registry-password: ${{ secrets.acr_azuredemocontainer_password }}
        secret-name: azureaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: azureaks90f9
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          azuredemocontainer.azurecr.io/azureaks:${{ github.sha }}
        imagepullsecrets: |
          azureaksdockerauth
